// gamesList.js
export const gamesList = [
    "The Legend of Zelda: Breath of the Wild",
    "Super Mario Odyssey",
    "Red Dead Redemption 2",
    "The Witcher 3: Wild Hunt",
    "God of War",
    "Minecraft",
    "Fortnite",
    "Grand Theft Auto V",
    "Overwatch",
    "League of Legends",
    "Dark Souls III",
    "Call of Duty: Modern Warfare",
    "Apex Legends",
    "Cyberpunk 2077",
    "Animal Crossing: New Horizons",
    "Among Us",
    "Valorant",
    "Hades",
    "Assassin's Creed Valhalla",
    "Ghost of Tsushima",
    "Hollow Knight",
    "Celeste",
    "Doom Eternal",
    "Half-Life: Alyx",
    "Final Fantasy VII Remake",
    "Resident Evil Village",
    "Monster Hunter: World",
    "Persona 5",
    "Sekiro: Shadows Die Twice",
    "Bloodborne",
    "Stardew Valley",
    "Horizon Zero Dawn",
    "The Last of Us Part II",
    "Uncharted 4: A Thief's End",
    "Nier: Automata",
    "Control",
    "Destiny 2",
    "Spider-Man: Miles Morales",
    "Genshin Impact",
    "Subnautica",
    "Outer Wilds",
    "Ori and the Will of the Wisps",
    "Cuphead",
    "Dead Cells",
    "Divinity: Original Sin II",
    "Slay the Spire",
    "Disco Elysium",
    "Star Wars Jedi: Fallen Order",
    "Fire Emblem: Three Houses",
    "Super Smash Bros. Ultimate",
    "Splatoon 2",
    "Mario Kart 8 Deluxe",
    "Rocket League",
    "The Sims 4",
    "Terraria",
    "Halo: The Master Chief Collection",
    "Path of Exile",
    "Civilization VI",
    "Sid Meier's Civilization V",
    "Dragon Age: Inquisition",
    "The Elder Scrolls V: Skyrim",
    "Fallout 4",
    "Bioshock Infinite",
    "Mass Effect 3",
    "Mass Effect 2",
    "Journey",
    "Inside",
    "Limbo",
    "Portal 2",
    "The Stanley Parable",
    "Gone Home",
    "What Remains of Edith Finch",
    "Firewatch",
    "Oxenfree",
    "Life is Strange",
    "Life is Strange: Before the Storm",
    "Life is Strange 2",
    "Telltale's The Walking Dead",
    "Telltale's The Wolf Among Us",
    "Batman: Arkham City",
    "Batman: Arkham Knight",
    "Injustice 2",
    "Mortal Kombat 11",
    "Tekken 7",
    "Street Fighter V",
    "Guilty Gear Strive",
    "BlazBlue: Cross Tag Battle",
    "Soulcalibur VI",
    "Dead or Alive 6",
    "Granblue Fantasy: Versus",
    "Dragon Ball FighterZ",
    "Dota 2",
    "Team Fortress 2",
    "Counter-Strike: Global Offensive",
    "Warframe",
    "Rainbow Six Siege",
    "PUBG: Battlegrounds",
    "Battlefield V",
    "Battlefield 1",
    "Titanfall 2",
    "Borderlands 3",
    "Borderlands 2",
    "XCOM 2",
    "XCOM: Enemy Unknown",
    "Frostpunk",
    "Into the Breach",
    "Total War: Three Kingdoms",
    "Total War: Warhammer II",
    "Total War: Shogun 2",
    "Company of Heroes 2",
    "Age of Empires II: Definitive Edition",
    "Age of Empires III: Definitive Edition",
    "StarCraft II",
    "Warcraft III: Reforged",
    "Diablo III",
    "Torchlight II",
    "Pillars of Eternity II: Deadfire",
    "Pillars of Eternity",
    "Wasteland 3",
    "Wasteland 2",
    "Baldur's Gate III",
    "Baldur's Gate II: Enhanced Edition",
    "Planescape: Torment: Enhanced Edition",
    "Icewind Dale: Enhanced Edition",
    "The Outer Worlds",
    "The Surge 2",
    "The Surge",
    "Nioh 2",
    "Nioh",
    "Yakuza: Like a Dragon",
    "Yakuza 0",
    "Yakuza Kiwami",
    "Yakuza Kiwami 2",
    "Judgment",
    "Sleeping Dogs",
    "Saints Row IV",
    "Saints Row: The Third",
    "Mafia: Definitive Edition",
    "Mafia III",
    "Mafia II: Definitive Edition",
    "Watch Dogs: Legion",
    "Watch Dogs 2",
    "Watch Dogs",
    "Tom Clancy's The Division 2",
    "Tom Clancy's The Division",
    "Destiny",
    "Anthem",
    "Marvel's Avengers",
    "No Man's Sky",
    "Elite Dangerous",
    "Star Citizen",
    "Star Wars: Squadrons",
    "Star Wars: Battlefront II",
    "Star Wars: Battlefront",
    "Call of Duty: Black Ops Cold War",
    "Call of Duty: Black Ops 4",
    "Call of Duty: Black Ops III",
    "Call of Duty: WWII",
    "Call of Duty: Infinite Warfare",
    "Call of Duty: Advanced Warfare",
    "Call of Duty: Ghosts",
    "Far Cry 5",
    "Far Cry 4",
    "Far Cry 3",
    "Far Cry Primal",
    "Metro Exodus",
    "Metro: Last Light",
    "Metro 2033",
    "Dishonored 2",
    "Dishonored",
    "Prey",
    "Deus Ex: Mankind Divided",
    "Deus Ex: Human Revolution",
    "Thief",
    "Hitman 3",
    "Hitman 2",
    "Hitman",
    "Just Cause 4",
    "Just Cause 3",
    "Just Cause 2",
    "Mad Max",
    "Middle-earth: Shadow of War",
    "Middle-earth: Shadow of Mordor",
    "LA Noire",
    "Heavy Rain",
    "Beyond: Two Souls",
    "Detroit: Become Human",
    "Until Dawn",
    "The Dark Pictures Anthology: Man of Medan",
    "The Dark Pictures Anthology: Little Hope",
    "The Dark Pictures Anthology: House of Ashes",
    "Days Gone",
    "The Order: 1886",
    "Infamous Second Son",
    "Infamous First Light",
    "Ratchet & Clank: Rift Apart",
    "Ratchet & Clank",
    "Spyro Reignited Trilogy",
    "Crash Bandicoot N. Sane Trilogy",
    "Crash Bandicoot 4: It's About Time",
    "Crash Team Racing Nitro-Fueled",
    "Spyro the Dragon",
    "Spyro 2: Ripto's Rage!",
    "Spyro: Year of the Dragon",
    "Crash Bandicoot",
    "Crash Bandicoot 2: Cortex Strikes Back",
    "Crash Bandicoot: Warped",
    "Final Fantasy XV",
    "Final Fantasy XIV",
    "Final Fantasy XIII",
    "Final Fantasy XII: The Zodiac Age",
    "Final Fantasy X/X-2 HD Remaster",
    "Final Fantasy IX",
    "Final Fantasy VIII Remastered",
    "Final Fantasy VII",
    "Final Fantasy VI",
    "Final Fantasy V",
    "Final Fantasy IV",
    "Final Fantasy III",
    "Final Fantasy II",
    "Final Fantasy",
    "Kingdom Hearts III",
    "Kingdom Hearts II",
    "Kingdom Hearts",
    "Kingdom Hearts: Chain of Memories",
    "Kingdom Hearts 358/2 Days",
    "Kingdom Hearts Birth by Sleep",
    "Kingdom Hearts Dream Drop Distance",
    "Kingdom Hearts Union χ[Cross]",
    "Kingdom Hearts Dark Road",
    "Persona 5 Royal",
    "Persona 4 Golden",
    "Persona 3 FES",
    "Shin Megami Tensei III: Nocturne HD Remaster",
    "Shin Megami Tensei IV",
    "Shin Megami Tensei V",
    "Shin Megami Tensei: Strange Journey Redux",
    "Shin Megami Tensei: Devil Survivor Overclocked",
    "Shin Megami Tensei: Devil Survivor 2 Record Breaker",
    "Shin Megami Tensei: Devil Summoner: Soul Hackers",
    "Shin Megami Tensei: Digital Devil Saga",
    "Shin Megami Tensei: Digital Devil Saga 2",
    "Bravely Default II",
    "Bravely Second: End Layer",
    "Bravely Default",
    "Octopath Traveler",
    "Triangle Strategy",
    "Project Triangle Strategy",
    "Tactics Ogre: Reborn",
    "Tactics Ogre: Let Us Cling Together",
    "Fire Emblem: Awakening",
    "Fire Emblem: Fates",
    "Fire Emblem: Echoes",
    "Fire Emblem: Path of Radiance",
    "Fire Emblem: Radiant Dawn",
    "Fire Emblem: Shadow Dragon",
    "Fire Emblem: The Blazing Blade",
    "Fire Emblem: The Sacred Stones",
    "Advance Wars 1+2: Re-Boot Camp",
    "Advance Wars: Dual Strike",
    "Advance Wars: Days of Ruin",
    "Final Fantasy Tactics: The War of the Lions",
    "Final Fantasy Tactics Advance",
    "Final Fantasy Tactics A2: Grimoire of the Rift",
    "Valkyria Chronicles 4",
    "Valkyria Chronicles Remastered",
    "Valkyria Chronicles III",
    "Valkyria Chronicles II",
    "Valkyria Chronicles",
    "Metal Gear Solid V: The Phantom Pain",
    "Metal Gear Solid IV: Guns of the Patriots",
    "Metal Gear Solid III: Snake Eater",
    "Metal Gear Solid II: Sons of Liberty",
    "Metal Gear Solid",
    "Metal Gear Rising: Revengeance",
    "Silent Hill 2",
    "Silent Hill 3",
    "Silent Hill 4: The Room",
    "Silent Hill",
    "Silent Hill: Shattered Memories",
    "Resident Evil 2",
    "Resident Evil 3",
    "Resident Evil 4",
    "Resident Evil 5",
    "Resident Evil 6",
    "Resident Evil 7: Biohazard",
    "Resident Evil 0",
    "Resident Evil Code: Veronica X",
    "Resident Evil: Revelations",
    "Resident Evil: Revelations 2",
    "Resident Evil: The Darkside Chronicles",
    "Resident Evil: The Umbrella Chronicles",
    "Resident Evil: Operation Raccoon City",
    "Resident Evil Outbreak",
    "Dead Rising",
    "Dead Rising 2",
    "Dead Rising 3",
    "Dead Rising 4",
    "Left 4 Dead",
    "Left 4 Dead 2",
    "Back 4 Blood",
    "The Evil Within",
    "The Evil Within 2",
    "Outlast",
    "Outlast 2",
    "Amnesia: The Dark Descent",
    "Amnesia: A Machine for Pigs",
    "Amnesia: Rebirth",
    "SOMA",
    "Layers of Fear",
    "Layers of Fear 2",
    "Observer",
    "Observer: System Redux",
    "Blair Witch",
    "Alien: Isolation",
    "Dying Light",
    "Dying Light 2",
    "Dead by Daylight",
    "Friday the 13th: The Game",
    "Phasmophobia",
    "Devour",
    "The Forest",
    "The Forest 2",
    "Rust",
    "DayZ",
    "ARK: Survival Evolved",
    "Conan Exiles",
    "7 Days to Die",
    "Subnautica: Below Zero",
    "Raft",
    "The Long Dark",
    "Don't Starve",
    "Don't Starve Together",
    "Oxygen Not Included",
    "This War of Mine",
    "Banished",
    "Farming Simulator 22",
    "Farming Simulator 19",
    "Farming Simulator 17",
    "Farming Simulator 15",
    "Harvest Moon: Light of Hope",
    "Harvest Moon: One World",
    "Harvest Moon: Friends of Mineral Town",
    "Harvest Moon: Back to Nature",
    "Harvest Moon: A Wonderful Life",
    "Harvest Moon: Another Wonderful Life",
    "Harvest Moon: Magical Melody",
    "Harvest Moon: Animal Parade",
    "Harvest Moon: Tree of Tranquility",
    "Harvest Moon: Sunshine Islands",
    "Harvest Moon: Island of Happiness",
    "Harvest Moon DS",
    "Harvest Moon DS: Sunshine Islands",
    "Harvest Moon DS: Island of Happiness",
    "Harvest Moon DS: Grand Bazaar",
    "Harvest Moon DS: The Tale of Two Towns",
    "Story of Seasons",
    "Story of Seasons: Friends of Mineral Town",
    "Story of Seasons: Trio of Towns",
    "Story of Seasons: Pioneers of Olive Town",
    "Story of Seasons: A Wonderful Life",
    "Story of Seasons: Doraemon",
    "Rune Factory 4",
    "Rune Factory 4 Special",
    "Rune Factory 3",
    "Rune Factory: Frontier",
    "Rune Factory: Tides of Destiny",
    "My Time at Portia",
    "My Time at Sandrock",
    "Port Royale 4",
    "Port Royale 3",
    "Port Royale 2",
    "Anno 1800",
    "Anno 2205",
    "Anno 2070",
    "Anno 1404",
    "Anno 1701",
    "Anno 1602",
    "The Settlers III",
    "The Settlers IV",
    "The Settlers V",
    "The Settlers VI",
    "The Settlers VII",
    "The Settlers II",
    "The Settlers",
    "SimCity 4",
    "SimCity 3000",
    "SimCity 2000",
    "SimCity",
    "Cities: Skylines",
    "Cities: Skylines II",
    "Planet Coaster",
    "Planet Zoo",
    "Jurassic World Evolution",
    "Jurassic World Evolution 2",
    "RollerCoaster Tycoon",
    "RollerCoaster Tycoon 2",
    "RollerCoaster Tycoon 3",
    "RollerCoaster Tycoon 4",
    "RollerCoaster Tycoon World",
    "Zoo Tycoon",
    "Zoo Tycoon 2",
    "Zoo Tycoon: Ultimate Animal Collection",
    "Theme Hospital",
    "Two Point Hospital",
    "Two Point Campus",
    "The Sims",
    "The Sims 2",
    "The Sims 3",
    "The Sims Medieval",
    "The Sims FreePlay",
    "The Sims Mobile",
    "Cooking Simulator",
    "House Flipper",
    "PowerWash Simulator",
    "PC Building Simulator",
    "Thief Simulator",
    "Car Mechanic Simulator",
    "Fishing Planet",
    "Euro Truck Simulator 2",
    "American Truck Simulator",
    "SnowRunner",
    "MudRunner",
    "Bus Simulator 21",
    "Train Simulator 2022",
    "Train Sim World 2",
    "Flight Simulator",
    "Microsoft Flight Simulator X",
    "X-Plane 11",
    "DCS World",
    "Kerbal Space Program",
    "Kerbal Space Program 2",
    "Eve Online",
    "Space Engineers",
    "Empyrion - Galactic Survival",
    "Surviving Mars",
    "RimWorld",
    "Factorio",
    "Satisfactory",
    "Dyson Sphere Program",
    "Astroneer",
    "Minecraft Dungeons",
    "Lego Worlds",
    "Lego City Undercover",
    "Lego Marvel Super Heroes",
    "Lego Marvel Super Heroes 2",
    "Lego Marvel's Avengers",
    "Lego Star Wars: The Skywalker Saga",
    "Lego Star Wars: The Force Awakens",
    "Lego Star Wars: The Complete Saga",
    "Lego Star Wars II: The Original Trilogy",
    "Lego Star Wars",
    "Lego Batman",
    "Lego Batman 2: DC Super Heroes",
    "Lego Batman 3: Beyond Gotham",
    "Lego DC Super-Villains",
    "Lego Harry Potter: Years 1-4",
    "Lego Harry Potter: Years 5-7",
    "Lego Indiana Jones: The Original Adventures",
    "Lego Indiana Jones 2: The Adventure Continues",
    "Lego Jurassic World",
    "Lego Pirates of the Caribbean",
    "Lego The Hobbit",
    "Lego The Incredibles",
    "Lego The Lord of the Rings",
    "Lego Dimensions",
    "Undertale",
    "Ori and the Blind Forest",
    "The Messenger",
    "Shovel Knight",
    "Katana Zero",
    "Axiom Verge",
    "Hyper Light Drifter",
    "The Binding of Isaac",
    "Starbound",
    "Prison Architect",
    "Tropico 6",
    "Tropico 5",
    "Tropico 4",
    "Tropico 3",
    "Half-Life",
    "Half-Life 2",
    "Portal",
]